/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/AdminScreen`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/CadastroScreen`; params?: Router.UnknownInputParams; } | { pathname: `/controlepresao`; params?: Router.UnknownInputParams; } | { pathname: `/dailycontrol`; params?: Router.UnknownInputParams; } | { pathname: `/DailyControlScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/InfoFamilia`; params?: Router.UnknownInputParams; } | { pathname: `/OrientacoesMedicas`; params?: Router.UnknownInputParams; } | { pathname: `/ResumoPaciente`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/AdminScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/CadastroScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/controlepresao`; params?: Router.UnknownOutputParams; } | { pathname: `/dailycontrol`; params?: Router.UnknownOutputParams; } | { pathname: `/DailyControlScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/InfoFamilia`; params?: Router.UnknownOutputParams; } | { pathname: `/OrientacoesMedicas`; params?: Router.UnknownOutputParams; } | { pathname: `/ResumoPaciente`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin${`?${string}` | `#${string}` | ''}` | `/AdminScreen${`?${string}` | `#${string}` | ''}` | `/cadastro${`?${string}` | `#${string}` | ''}` | `/CadastroScreen${`?${string}` | `#${string}` | ''}` | `/controlepresao${`?${string}` | `#${string}` | ''}` | `/dailycontrol${`?${string}` | `#${string}` | ''}` | `/DailyControlScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/InfoFamilia${`?${string}` | `#${string}` | ''}` | `/OrientacoesMedicas${`?${string}` | `#${string}` | ''}` | `/ResumoPaciente${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/AdminScreen`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/CadastroScreen`; params?: Router.UnknownInputParams; } | { pathname: `/controlepresao`; params?: Router.UnknownInputParams; } | { pathname: `/dailycontrol`; params?: Router.UnknownInputParams; } | { pathname: `/DailyControlScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/InfoFamilia`; params?: Router.UnknownInputParams; } | { pathname: `/OrientacoesMedicas`; params?: Router.UnknownInputParams; } | { pathname: `/ResumoPaciente`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
